name: CD Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create project archive
        run: |
          zip -r GLUD-Git.zip . -x "venv/*" ".git/*"

      - name: Create GitHub Release
        uses: actions/create-release@v4
        with:
          files: GLUD-Git.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
